// FOR TASKS
export const CREATE_TASK = 'CREATE_TASK';
export const READTE_TASK = 'READTE_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const UPDATE_TASK = 'UPDATE_TASK';

// FOR COMMENTS
export const CREATE_COMMENT = 'CREATE_COMMENT';
export const READTE_COMMENT = 'READTE_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const UPDATE_COMMENT = 'UPDATE_COMMENT';

// FOR LISTS
export const CREATE_LIST = 'CREATE_LIST';
export const READTE_LIST = 'READTE_LIST';
export const DELETE_LIST = 'DELETE_LIST';
export const UPDATE_LIST = 'UPDATE_LIST';

// FOR BOARDS
export const CREATE_BOARD = 'CREATE_BOARD';
export const READTE_BOARD = 'READTE_BOARD';
export const DELETE_BOARD = 'DELETE_BOARD';
export const UPDATE_BOARD = 'UPDATE_BOARD';

// FOR USERS
export const CREATE_USER = 'CREATE_USER';
export const READTE_USER = 'READTE_USER';
export const DELETE_USER = 'DELETE_USER';
export const UPDATE_USER = 'UPDATE_USER';