// FOR INITIALIZING STATE
export const INIT_STATE = 'INIT_STATE';

// FOR TASKS
export const CREATE_TASK = 'CREATE_TASK';
export const READTE_TASK = 'READTE_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const UPDATE_TASK = 'UPDATE_TASK';
